# Generated by Django 4.2.4 on 2023-08-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=50)),
                ('phone_no', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='entry')),
            ],
        ),
    ]
